blank_issues_enabled: false
contact_links:
  - name: ⚠️ Application issue
    url: https://github.com/bigbabyboost/shiori/issues/new/choose
    about: Issues and requests about the app itself should be opened in the shiori repository instead
  - name: ⚠️ Extensions issue
    url: https://github.com/bigbabyboost/shiori-extensions/issues/new/choose
    about: Issues and requests about the app itself should be opened in the Shiori-Extensions repository instead
  - name: 🖥️ Shiori website
    url: https://bigbabyboost.github.io/
    about: Guides, troubleshooting, and answers to common questions
